/**Application constant */
export const UPDATE_SELECTED_TEMPLATE = 'UPDATE_SELECTED_TEMPLATE'
export const FETCH_SELECTED_TEMPLATE = 'FETCH_SELECTED_TEMPLATE'


export const UPDATE_DATA = 'UPDATE_DATA';
export const UPDATE_TEMPLATE_DATA = 'UPDATE_TEMPLATE_DATA';
export const UPDATE_FACILITY_DATA = 'UPDATE_FACILITY_DATA';
export const UPDATE_CONTACT_DATA = 'UPDATE_CONTACT_DATA';
export const UPDATE_NEWS_DATA = 'UPDATE_NEWS_DATA';
export const UPDATE_EVENTS_DATA = 'UPDATE_EVENTS_DATA';
export const UPDATE_ADMISSION_PROCESS_DATA = 'UPDATE_ADMISSION_PROCESS_DATA';
export const UPDATE_TEACHING_DATA = 'UPDATE_TEACHING_DATA';
export const UPDATE_RULES_DATA = 'UPDATE_RULES_DATA';
export const UPDATE_CURICULLUM_DATA = 'UPDATE_CURICULLUM_DATA';
export const UPDATE_HEADER_DATA = 'UPDATE_HEADER_DATA';
export const UPDATE_NAVBAR_DATA = 'UPDATE_NAVBAR_DATA';
export const UPDATE_COMMITTEE_DATA = 'UPDATE_COMMITTEE_DATA';
export const UPDATE_MISSION_DATA = 'UPDATE_MISSION_DATA';
export const UPDATE_PRINCIPAL_MESSAGE_DATA = 'UPDATE_PRINCIPAL_MESSAGE_DATA';
export const UPDATE_TEACHER_DATA = 'UPDATE_TEACHER_DATA';
export const UPDATE_STRENGTH_DATA = 'UPDATE_STRENGTH_DATA';
export const UPDATE_VIDEO_DATA = 'UPDATE_VIDEO_DATA';
export const UPDATE_FOOTER_DATA = 'UPDATE_FOOTER_DATA';

export const UPDATE_TEACHING_TEMPLATE_DATA = 'UPDATE_TEACHING_TEMPLATE_DATA';
export const UPDATE_RULES_TEMPLATE_DATA = 'UPDATE_RULES_TEMPLATE_DATA';
export const UPDATE_NEWS_TEMPLATE_DATA = 'UPDATE_NEWS_TEMPLATE_DATA';
export const UPDATE_EVENTS_TEMPLATE_DATA = 'UPDATE_EVENTS_TEMPLATE_DATA';
export const UPDATE_FACILITY_TEMPLATE_DATA = 'UPDATE_FACILITY_TEMPLATE_DATA';
export const UPDATE_CURICULLUM_TEMPLATE_DATA = 'UPDATE_CURICULLUM_TEMPLATE_DATA';
export const UPDATE_CONTACT_TEMPLATE_DATA = 'UPDATE_CONTACT_TEMPLATE_DATA';
export const UPDATE_ADMISSION_PROCESS_TEMPLATE_DATA = 'UPDATE_ADMISSION_PROCESS_TEMPLATE_DATA';
export const UPDATE_HEADER_TEMPLATE_DATA = 'UPDATE_HEADER_TEMPLATE_DATA';
export const UPDATE_NAVBAR_TEMPLATE_DATA = 'UPDATE_NAVBAR_TEMPLATE_DATA';
export const UPDATE_COMMITTEE_TEMPLATE_DATA = 'UPDATE_COMMITTEE_TEMPLATE_DATA';
export const UPDATE_MISSION_TEMPLATE_DATA = 'UPDATE_MISSION_TEMPLATE_DATA';
export const UPDATE_PRINCIPAL_MESSAGE_TEMPLATE_DATA = 'UPDATE_PRINCIPAL_MESSAGE_TEMPLATE_DATA';
export const UPDATE_TEACHER_TEMPLATE_DATA = 'UPDATE_TEACHER_TEMPLATE_DATA';
export const UPDATE_STRENGTH_TEMPLATE_DATA = 'UPDATE_STRENGTH_TEMPLATE_DATA';
export const UPDATE_VIDEO_TEMPLATE_DATA = 'UPDATE_VIDEO_TEMPLATE_DATA';
export const UPDATE_FOOTER_TEMPLATE_DATA = 'UPDATE_FOOTER_TEMPLATE_DATA';
/**Screen */

export const UPDATE_SCREEN_DATA = 'UPDATE_SCREEN_DATA';

/**Auth constant */

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS'; 
export const AUTH_FAIL = 'AUTH_FAIL';  
export const AUTH_LOGOUT = 'AUTH_LOGOUT'; 
export const AUTH_REDIRECT_PATH = 'AUTH_REDIRECT_PATH';


/**Not using */
export const UPDATE_ALUMNI_DATA = 'UPDATE_ALUMNI_DATA';
export const DISPLAY_TOASTER = 'DISPLAY_TOASTER';
export const DISPLAY_MODAL = 'DISPLAY_MODAL';
export const DISPLAY_SECTION_MODAL = 'DISPLAY_SECTION_MODAL';